s1=raw_input("enter the name:")
s2=raw_input("enter the name:")
print"to capitalize the first character",s1.capitalize()
print"to capitalize the second character",s2.capitalize()
print s1.capitalize()
print s2.capitalize()
